// ── Toppturfinner — Turdatabase ──
// Kjente splitboard-/randonee-turer i Hemsedal, Jotunheimen, Hurrungane og Sunnmorsalpane.
// Koordinater: WGS84 (lat/lon desimalgrader).
// Kilde for koordinater: Geonorge stedsnavn-API (ws.geonorge.no)

const TOURS = [
    // ═══════════════════════════════════════
    // HEMSEDAL (Varsom region 3027 Hallingdal)
    // ═══════════════════════════════════════
    {
        id: "hemsedal_tinden",
        name: "Hemsedal Tinden (Storetinden)",
        region: "Hemsedal",
        varsom_region_id: 3027,
        start: { lat: 60.8618, lon: 8.5635, name: "Hemsedal sentrum P" },
        summit: { lat: 60.8780, lon: 8.5650, elevation: 1487 },
        vertical_gain: 950,
        slope_avg_deg: 25,
        aspect: "NE",
        difficulty: "middels",
        description: "Klassiker i Hemsedal. Bredt, aapent terreng med flere rennevalg.",
    },
    {
        id: "rogjin",
        name: "Rogjin",
        region: "Hemsedal",
        varsom_region_id: 3027,
        start: { lat: 60.8690, lon: 8.4970, name: "Hydnestolen P" },
        summit: { lat: 60.8543, lon: 8.4583, elevation: 1523 },
        vertical_gain: 850,
        slope_avg_deg: 22,
        aspect: "E",
        difficulty: "lett-middels",
        description: "Populaer tur med jevn stigning. Godt egnet for nybegynnere.",
    },
    {
        id: "skogshorn",
        name: "Skogshorn",
        region: "Hemsedal",
        varsom_region_id: 3027,
        start: { lat: 60.8730, lon: 8.6800, name: "Skogshorn P" },
        summit: { lat: 60.8815, lon: 8.6948, elevation: 1728 },
        vertical_gain: 1100,
        slope_avg_deg: 28,
        aspect: "SE",
        difficulty: "middels-krevende",
        description: "Ikonisk fjell med bratt topparti. Fantastisk utsikt over Hemsedal.",
    },
    {
        id: "vesletinden_hemsedal",
        name: "Vesletinden",
        region: "Hemsedal",
        varsom_region_id: 3027,
        start: { lat: 60.8680, lon: 8.5600, name: "Grondalen P" },
        summit: { lat: 60.8820, lon: 8.5400, elevation: 1325 },
        vertical_gain: 650,
        slope_avg_deg: 20,
        aspect: "N",
        difficulty: "lett",
        description: "Fin nybegynnertur med moderat terreng.",
    },
    {
        id: "ranastongi",
        name: "Ranastongi",
        region: "Hemsedal",
        varsom_region_id: 3027,
        start: { lat: 60.9900, lon: 8.5100, name: "Eldrevatn P" },
        summit: { lat: 61.0184, lon: 8.5095, elevation: 1414 },
        vertical_gain: 800,
        slope_avg_deg: 24,
        aspect: "NW",
        difficulty: "middels",
        description: "Rolig tur med god tilgang til variert terreng.",
    },
    {
        id: "storehoe",
        name: "Storeho",
        region: "Hemsedal",
        varsom_region_id: 3027,
        start: { lat: 60.9060, lon: 8.4800, name: "Tuv P" },
        summit: { lat: 60.9200, lon: 8.4500, elevation: 1546 },
        vertical_gain: 900,
        slope_avg_deg: 20,
        aspect: "SE",
        difficulty: "lett-middels",
        description: "Oversiktlig terreng med god oversikt. Trygt valg i usikre forhold.",
    },
    {
        id: "groendalsfjellet",
        name: "Grondalsfjellet",
        region: "Hemsedal",
        varsom_region_id: 3027,
        start: { lat: 60.8680, lon: 8.5600, name: "Grondalen P" },
        summit: { lat: 60.8850, lon: 8.5900, elevation: 1380 },
        vertical_gain: 700,
        slope_avg_deg: 18,
        aspect: "NW",
        difficulty: "lett",
        description: "Kort og enkel tur med fine skiforhold. Bra alternativ for familier.",
    },
    {
        id: "hemsedalsfjellet",
        name: "Hemsedalsfjellet via Solheisen",
        region: "Hemsedal",
        varsom_region_id: 3027,
        start: { lat: 60.8690, lon: 8.5300, name: "Solheisen P" },
        summit: { lat: 60.8900, lon: 8.5000, elevation: 1580 },
        vertical_gain: 1000,
        slope_avg_deg: 26,
        aspect: "N",
        difficulty: "middels",
        description: "Variert tur fra skisenteret med tilgang til bakketerreng og off-piste.",
    },
    {
        id: "hydnefossen",
        name: "Hydnefossen-omraadet",
        region: "Hemsedal",
        varsom_region_id: 3027,
        start: { lat: 60.8690, lon: 8.4970, name: "Hydnestolen P" },
        summit: { lat: 60.8800, lon: 8.4600, elevation: 1610 },
        vertical_gain: 950,
        slope_avg_deg: 24,
        aspect: "NE",
        difficulty: "middels",
        description: "Spektakulaert terreng naer Hydnefossen. Flere rennevalg i bratt fjellside.",
    },

    // ═══════════════════════════════════════
    // JOTUNHEIMEN (Varsom region 3028)
    // ═══════════════════════════════════════
    {
        id: "leirvassbu_area",
        name: "Kyrkja fra Leirvassbu",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.5486, lon: 8.2476, name: "Leirvassbu" },
        summit: { lat: 61.5414, lon: 8.2920, elevation: 2032 },
        vertical_gain: 900,
        slope_avg_deg: 26,
        aspect: "S",
        difficulty: "middels-krevende",
        description: "Storslaatt alpint terreng. Kyrkja er en av Jotunheimens flotteste topper.",
    },
    {
        id: "bukkeholstinden",
        name: "Bukkeholstinden",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.5486, lon: 8.2476, name: "Leirvassbu" },
        summit: { lat: 61.5794, lon: 8.3073, elevation: 1860 },
        vertical_gain: 730,
        slope_avg_deg: 23,
        aspect: "NE",
        difficulty: "middels",
        description: "Fin tur fra Leirvassbu med oversiktlig terreng.",
    },
    {
        id: "storebjorn",
        name: "Storebjorn",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.6245, lon: 8.4048, name: "Spiterstulen" },
        summit: { lat: 61.5482, lon: 8.1371, elevation: 2222 },
        vertical_gain: 1100,
        slope_avg_deg: 20,
        aspect: "W",
        difficulty: "middels",
        description: "Lang tur over Smostabbtindane. Krever god navigering.",
    },
    {
        id: "besshoe",
        name: "Bessho",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.5250, lon: 8.7860, name: "Bessheim" },
        summit: { lat: 61.5179, lon: 8.6872, elevation: 2258 },
        vertical_gain: 1050,
        slope_avg_deg: 22,
        aspect: "E",
        difficulty: "middels",
        description: "Klassisk topptur fra Bessheim med fantastisk utsikt over Gjende.",
    },
    {
        id: "falketind",
        name: "Falketind",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.5044, lon: 7.8017, name: "Turtagro P" },
        summit: { lat: 61.3847, lon: 8.0967, elevation: 2067 },
        vertical_gain: 1300,
        slope_avg_deg: 27,
        aspect: "NW",
        difficulty: "krevende",
        description: "Krevende tur via Stolsmaradalen. Lang dag med bratt terreng og brepassering.",
    },
    {
        id: "knutsholstind",
        name: "Knutsholstinden",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.4941, lon: 8.8130, name: "Gjendesheim" },
        summit: { lat: 61.4244, lon: 8.5620, elevation: 2091 },
        vertical_gain: 960,
        slope_avg_deg: 25,
        aspect: "SW",
        difficulty: "middels-krevende",
        description: "Populaer topptur fra Gjendesheim via Memurubu. Fin nedkjoring paa sorsiden.",
    },
    {
        id: "memuru",
        name: "Memurutinden",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.4910, lon: 8.6311, name: "Memurubu" },
        summit: { lat: 61.5663, lon: 8.4830, elevation: 2366 },
        vertical_gain: 1250,
        slope_avg_deg: 28,
        aspect: "N",
        difficulty: "krevende",
        description: "Jotunheimens mest alpine topptur. Kun for erfarne i stabile forhold.",
    },
    {
        id: "galdhopiggen",
        name: "Galdhopiggen",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.6245, lon: 8.4048, name: "Spiterstulen" },
        summit: { lat: 61.6364, lon: 8.3125, elevation: 2469 },
        vertical_gain: 1350,
        slope_avg_deg: 18,
        aspect: "S",
        difficulty: "middels",
        description: "Norges hoyeste fjell. Lang, men moderat tur fra Spiterstulen. Brepassering.",
    },
    {
        id: "glittertind",
        name: "Glittertind",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.6245, lon: 8.4048, name: "Spiterstulen" },
        summit: { lat: 61.6512, lon: 8.5576, elevation: 2452 },
        vertical_gain: 1330,
        slope_avg_deg: 20,
        aspect: "W",
        difficulty: "middels",
        description: "Norges nest hoyeste. Jevne flanker med god skikjoring paa vaarsno.",
    },
    {
        id: "loftet",
        name: "Loftet",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.5486, lon: 8.2476, name: "Leirvassbu" },
        summit: { lat: 61.6229, lon: 8.1260, elevation: 2170 },
        vertical_gain: 1040,
        slope_avg_deg: 24,
        aspect: "SE",
        difficulty: "middels",
        description: "Oversiktlig tur fra Leirvassbu med brede flanker og fin utsikt mot Kyrkja.",
    },
    {
        id: "surtningssue",
        name: "Surtningssui",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.6245, lon: 8.4048, name: "Spiterstulen" },
        summit: { lat: 61.5341, lon: 8.5727, elevation: 2368 },
        vertical_gain: 1250,
        slope_avg_deg: 22,
        aspect: "NE",
        difficulty: "middels",
        description: "Rolig tur fra Spiterstulen med bra snoforhold utover vaaren.",
    },
    {
        id: "nore_illaabre",
        name: "Nordre Illaabreen",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.6245, lon: 8.4048, name: "Spiterstulen" },
        summit: { lat: 61.6199, lon: 8.2664, elevation: 2320 },
        vertical_gain: 1200,
        slope_avg_deg: 25,
        aspect: "S",
        difficulty: "middels-krevende",
        description: "Bratt bre-renne med paalitelig sno. Kort og intens nedkjoring.",
    },
    {
        id: "uradalsegga",
        name: "Uradalstindene",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.5486, lon: 8.2476, name: "Leirvassbu" },
        summit: { lat: 61.5410, lon: 8.3862, elevation: 2116 },
        vertical_gain: 980,
        slope_avg_deg: 27,
        aspect: "E",
        difficulty: "middels-krevende",
        description: "Alpin karakter med bratte renner paa ostsiden. Fin nedkjoring i pudder.",
    },
    {
        id: "svellnosbrean",
        name: "Svellnosbreen",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.6245, lon: 8.4048, name: "Spiterstulen" },
        summit: { lat: 61.6241, lon: 8.3107, elevation: 2210 },
        vertical_gain: 1090,
        slope_avg_deg: 19,
        aspect: "NW",
        difficulty: "middels",
        description: "Bred bre med jevn stigning. Trygt alternativ i usikre forhold.",
    },
    {
        id: "veotinden",
        name: "Veotinden",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.6245, lon: 8.4048, name: "Spiterstulen" },
        summit: { lat: 61.5762, lon: 8.5314, elevation: 2044 },
        vertical_gain: 920,
        slope_avg_deg: 26,
        aspect: "N",
        difficulty: "middels-krevende",
        description: "Kort, bratt tur rett fra Spiterstulen. Nordvendt renne holder snoen lenge.",
    },

    // ═══════════════════════════════════════
    // HURRUNGANE (Varsom region 3028 Jotunheimen)
    // ═══════════════════════════════════════
    {
        id: "store_skagastolstind",
        name: "Store Skagastolstind",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.5044, lon: 7.8017, name: "Turtagro P" },
        summit: { lat: 61.4612, lon: 7.8719, elevation: 2405 },
        vertical_gain: 1650,
        slope_avg_deg: 35,
        aspect: "SE",
        difficulty: "krevende",
        description: "Norges tredje hoyeste fjell. Svaert krevende splitboard-tur med bratt terreng og brepassering.",
    },
    {
        id: "dyrhaugstindane",
        name: "Dyrhaugstindane",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.5044, lon: 7.8017, name: "Turtagro P" },
        summit: { lat: 61.4578, lon: 7.8352, elevation: 2147 },
        vertical_gain: 1400,
        slope_avg_deg: 33,
        aspect: "NE",
        difficulty: "krevende",
        description: "Klassisk couloir-kjoring i Hurrungane. Bratte renner med alpin karakter.",
    },
    {
        id: "stolsnostind",
        name: "Stolsnostind",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.5044, lon: 7.8017, name: "Turtagro P" },
        summit: { lat: 61.3960, lon: 8.0713, elevation: 2074 },
        vertical_gain: 1300,
        slope_avg_deg: 27,
        aspect: "E",
        difficulty: "middels-krevende",
        description: "Populaer og tilgjengelig topptur i Hurrungane. Flott utsikt over Skagastolstindene.",
    },
    {
        id: "fannaraki",
        name: "Fannaraaki",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.5044, lon: 7.8017, name: "Turtagro P" },
        summit: { lat: 61.5167, lon: 7.9083, elevation: 2068 },
        vertical_gain: 1300,
        slope_avg_deg: 22,
        aspect: "W",
        difficulty: "middels",
        description: "Lang bre-tur fra Turtagro via Fannaraakbreen. Moderat terreng, men lang dag.",
    },
    {
        id: "midtmaradalsegga",
        name: "Store Midtmaradalstinden",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.5044, lon: 7.8017, name: "Turtagro P" },
        summit: { lat: 61.4419, lon: 7.8718, elevation: 2042 },
        vertical_gain: 1290,
        slope_avg_deg: 30,
        aspect: "N",
        difficulty: "krevende",
        description: "Alpin eggtravers i Hurrungane. Krevende terreng med eksponerte partier.",
    },
    {
        id: "ringstindane",
        name: "Store Ringstind",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.5044, lon: 7.8017, name: "Turtagro P" },
        summit: { lat: 61.4420, lon: 7.8007, elevation: 2124 },
        vertical_gain: 1370,
        slope_avg_deg: 32,
        aspect: "NE",
        difficulty: "krevende",
        description: "Bratt NO-side med god snosamling. Klassisk randonee for erfarne i Hurrungane.",
    },
    {
        id: "austanbotntind",
        name: "Austanbotntind",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.5044, lon: 7.8017, name: "Turtagro P" },
        summit: { lat: 61.4321, lon: 7.7921, elevation: 2203 },
        vertical_gain: 1450,
        slope_avg_deg: 30,
        aspect: "SW",
        difficulty: "krevende",
        description: "Bratt nedkjoring mot Bandet. Klassisk Hurrungane-tur for erfarne.",
    },
    {
        id: "sentraltind",
        name: "Sentraltind",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.5044, lon: 7.8017, name: "Turtagro P" },
        summit: { lat: 61.4637, lon: 7.8825, elevation: 2348 },
        vertical_gain: 1600,
        slope_avg_deg: 34,
        aspect: "W",
        difficulty: "krevende",
        description: "Teknisk krevende med bratt topparti. Stor fjellopplevelse i Hurrungane.",
    },

    // ═══════════════════════════════════════
    // SUNNMORSALPANE (Varsom region 3023 Romsdal)
    // ═══════════════════════════════════════
    {
        id: "slogen",
        name: "Slogen",
        region: "Sunnmorsalpane",
        varsom_region_id: 3023,
        start: { lat: 62.2129, lon: 6.5669, name: "Urke P" },
        summit: { lat: 62.2080, lon: 6.6730, elevation: 1564 },
        vertical_gain: 1564,
        slope_avg_deg: 28,
        aspect: "N",
        difficulty: "middels-krevende",
        description: "Ikonisk Sunnmore-topp rett fra fjorden. Spektakulaer nedkjoring til Norangsdalen.",
    },
    {
        id: "kolastinden",
        name: "Kolaastinden",
        region: "Sunnmorsalpane",
        varsom_region_id: 3023,
        start: { lat: 62.2479, lon: 6.3535, name: "Kolaastindhytta P" },
        summit: { lat: 62.2587, lon: 6.3106, elevation: 1432 },
        vertical_gain: 1100,
        slope_avg_deg: 26,
        aspect: "E",
        difficulty: "middels",
        description: "Populaer tur fra Kolaastindhytta. Bredt, aapent terreng med god snosikkerhet.",
    },
    {
        id: "saudehornet",
        name: "Saudehornet",
        region: "Sunnmorsalpane",
        varsom_region_id: 3023,
        start: { lat: 62.2076, lon: 6.4759, name: "Saebo P" },
        summit: { lat: 62.2869, lon: 6.5024, elevation: 1303 },
        vertical_gain: 1303,
        slope_avg_deg: 25,
        aspect: "NW",
        difficulty: "middels",
        description: "Klassisk fjord-til-topp med panoramautsikt over Hjorundfjorden.",
    },
    {
        id: "jakta",
        name: "Jakta",
        region: "Sunnmorsalpane",
        varsom_region_id: 3023,
        start: { lat: 62.2904, lon: 6.8399, name: "Strandafjellet P" },
        summit: { lat: 62.1710, lon: 6.6167, elevation: 1590 },
        vertical_gain: 1250,
        slope_avg_deg: 30,
        aspect: "NE",
        difficulty: "middels-krevende",
        description: "Bratt og krevende med fantastiske renner. Sunnmores mest kjente couloir-tur.",
    },
    {
        id: "brekketinden",
        name: "Brekketindane",
        region: "Sunnmorsalpane",
        varsom_region_id: 3023,
        start: { lat: 62.2904, lon: 6.8399, name: "Strandafjellet P" },
        summit: { lat: 62.2294, lon: 6.7044, elevation: 1480 },
        vertical_gain: 1150,
        slope_avg_deg: 28,
        aspect: "N",
        difficulty: "middels-krevende",
        description: "Fin eggtur med flere nedkjoringsalternativer. God snosamling nordvendt.",
    },
    {
        id: "dalegubben",
        name: "Dalegubben",
        region: "Sunnmorsalpane",
        varsom_region_id: 3023,
        start: { lat: 62.2010, lon: 6.4200, name: "Orsta P" },
        summit: { lat: 62.2304, lon: 6.4347, elevation: 1362 },
        vertical_gain: 1100,
        slope_avg_deg: 24,
        aspect: "W",
        difficulty: "middels",
        description: "Tilgjengelig tur med jevn stigning. Bra for dager med moderat vind.",
    },
    {
        id: "roaldshornet",
        name: "Roaldshornet",
        region: "Sunnmorsalpane",
        varsom_region_id: 3023,
        start: { lat: 62.3200, lon: 6.8500, name: "Roaldsoya P" },
        summit: { lat: 62.3116, lon: 6.8397, elevation: 1280 },
        vertical_gain: 1280,
        slope_avg_deg: 26,
        aspect: "SE",
        difficulty: "middels",
        description: "Enkel tilgang og god nedkjoring. Populaert maal for dagstur fra Aalesund.",
    },
    {
        id: "saksa",
        name: "Saksa",
        region: "Sunnmorsalpane",
        varsom_region_id: 3023,
        start: { lat: 62.2129, lon: 6.5669, name: "Urke P" },
        summit: { lat: 62.2310, lon: 6.5507, elevation: 1073 },
        vertical_gain: 1073,
        slope_avg_deg: 30,
        aspect: "S",
        difficulty: "middels-krevende",
        description: "Bratt fjellside med spektakulaer utsikt over Hjorundfjorden. Kort, men intens.",
    },
    {
        id: "smoerstabbtindane",
        name: "Smorstabbtindane",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.5486, lon: 8.2476, name: "Leirvassbu" },
        summit: { lat: 61.5717, lon: 8.1211, elevation: 1630 },
        vertical_gain: 1300,
        slope_avg_deg: 27,
        aspect: "NW",
        difficulty: "middels-krevende",
        description: "Alpint terreng med flere toppvalg. Lang dag i storslaatt landskap.",
    },
    {
        id: "kvitegga",
        name: "Kvitegga",
        region: "Sunnmorsalpane",
        varsom_region_id: 3023,
        start: { lat: 62.0855, lon: 6.8677, name: "Hellesylt P" },
        summit: { lat: 62.1386, lon: 6.8649, elevation: 1420 },
        vertical_gain: 1420,
        slope_avg_deg: 22,
        aspect: "SW",
        difficulty: "middels",
        description: "Lang, men moderat tur med fin utsikt over Geirangerfjorden.",
    },
];
