// ── Splitboard Finder — Tour Database ──
// Kjente splitboard-/randonee-turer i Hemsedal, Jotunheimen, Hurrungane og Sunnmorsalpane.
// Koordinater: WGS84 (lat/lon desimalgrader).

const TOURS = [
    // ═══════════════════════════════════════
    // HEMSEDAL (Varsom region 3027 Hallingdal)
    // ═══════════════════════════════════════
    {
        id: "hemsedal_tinden",
        name: "Hemsedal Tinden (Storetinden)",
        region: "Hemsedal",
        varsom_region_id: 3027,
        start: { lat: 60.8602, lon: 8.5595, name: "Hemsedal sentrum P" },
        summit: { lat: 60.8780, lon: 8.5650, elevation: 1487 },
        vertical_gain: 950,
        slope_avg_deg: 25,
        aspect: "NE",
        difficulty: "middels",
        description: "Klassiker i Hemsedal. Bredt, aapent terreng med flere rennevalg.",
    },
    {
        id: "rogjin",
        name: "Rogjin",
        region: "Hemsedal",
        varsom_region_id: 3027,
        start: { lat: 60.8690, lon: 8.4970, name: "Hydnestolen P" },
        summit: { lat: 60.8500, lon: 8.4500, elevation: 1523 },
        vertical_gain: 850,
        slope_avg_deg: 22,
        aspect: "E",
        difficulty: "lett-middels",
        description: "Populaer tur med jevn stigning. Godt egnet for nybegynnere.",
    },
    {
        id: "skogshorn",
        name: "Skogshorn",
        region: "Hemsedal",
        varsom_region_id: 3027,
        start: { lat: 60.8730, lon: 8.6800, name: "Skogshorn P" },
        summit: { lat: 60.8815, lon: 8.6948, elevation: 1728 },
        vertical_gain: 1100,
        slope_avg_deg: 28,
        aspect: "SE",
        difficulty: "middels-krevende",
        description: "Ikonisk fjell med bratt topparti. Fantastisk utsikt over Hemsedal.",
    },
    {
        id: "vesletinden_hemsedal",
        name: "Vesletinden",
        region: "Hemsedal",
        varsom_region_id: 3027,
        start: { lat: 60.8680, lon: 8.5600, name: "Grondalen P" },
        summit: { lat: 60.8820, lon: 8.5400, elevation: 1325 },
        vertical_gain: 650,
        slope_avg_deg: 20,
        aspect: "N",
        difficulty: "lett",
        description: "Fin nybegynnertur med moderat terreng.",
    },
    {
        id: "ranastongi",
        name: "Ranastongi",
        region: "Hemsedal",
        varsom_region_id: 3027,
        start: { lat: 60.8400, lon: 8.5200, name: "Ulsaak P" },
        summit: { lat: 60.8250, lon: 8.4900, elevation: 1414 },
        vertical_gain: 800,
        slope_avg_deg: 24,
        aspect: "NW",
        difficulty: "middels",
        description: "Rolig tur med god tilgang til variert terreng.",
    },
    {
        id: "totteskogen",
        name: "Totteskogen",
        region: "Hemsedal",
        varsom_region_id: 3027,
        start: { lat: 60.8680, lon: 8.5600, name: "Grondalen P" },
        summit: { lat: 60.8600, lon: 8.5200, elevation: 1450 },
        vertical_gain: 780,
        slope_avg_deg: 22,
        aspect: "W",
        difficulty: "lett-middels",
        description: "Fin tur i skoggrensen med trygge nedkjoringer i Grondalen.",
    },
    {
        id: "storehoe",
        name: "Storeho",
        region: "Hemsedal",
        varsom_region_id: 3027,
        start: { lat: 60.9060, lon: 8.4800, name: "Tuv P" },
        summit: { lat: 60.9200, lon: 8.4500, elevation: 1546 },
        vertical_gain: 900,
        slope_avg_deg: 20,
        aspect: "SE",
        difficulty: "lett-middels",
        description: "Oversiktlig terreng med god oversikt. Trygt valg i usikre forhold.",
    },
    {
        id: "groendalsfjellet",
        name: "Grondalsfjellet",
        region: "Hemsedal",
        varsom_region_id: 3027,
        start: { lat: 60.8680, lon: 8.5600, name: "Grondalen P" },
        summit: { lat: 60.8850, lon: 8.5900, elevation: 1380 },
        vertical_gain: 700,
        slope_avg_deg: 18,
        aspect: "NW",
        difficulty: "lett",
        description: "Kort og enkel tur med fine skiforhold. Bra alternativ for familier.",
    },
    {
        id: "hemsedalsfjellet",
        name: "Hemsedalsfjellet via Solheisen",
        region: "Hemsedal",
        varsom_region_id: 3027,
        start: { lat: 60.8690, lon: 8.5300, name: "Solheisen P" },
        summit: { lat: 60.8900, lon: 8.5000, elevation: 1580 },
        vertical_gain: 1000,
        slope_avg_deg: 26,
        aspect: "N",
        difficulty: "middels",
        description: "Variert tur fra skisenteret med tilgang til bakketerreng og off-piste.",
    },
    {
        id: "hydnefossen",
        name: "Hydnefossen-omraadet",
        region: "Hemsedal",
        varsom_region_id: 3027,
        start: { lat: 60.8690, lon: 8.4970, name: "Hydnestolen P" },
        summit: { lat: 60.8800, lon: 8.4600, elevation: 1610 },
        vertical_gain: 950,
        slope_avg_deg: 24,
        aspect: "NE",
        difficulty: "middels",
        description: "Spektakulaert terreng naer Hydnefossen. Flere rennevalg i bratt fjellside.",
    },

    // ═══════════════════════════════════════
    // JOTUNHEIMEN (Varsom region 3028)
    // ═══════════════════════════════════════
    {
        id: "leirvassbu_area",
        name: "Kyrkja fra Leirvassbu",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.5500, lon: 8.2500, name: "Leirvassbu" },
        summit: { lat: 61.5400, lon: 8.2900, elevation: 2032 },
        vertical_gain: 900,
        slope_avg_deg: 26,
        aspect: "S",
        difficulty: "middels-krevende",
        description: "Storslaatt alpint terreng. Kyrkja er en av Jotunheimens flotteste topper.",
    },
    {
        id: "bukkeholstinden",
        name: "Bukkeholstinden",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.5500, lon: 8.2500, name: "Leirvassbu" },
        summit: { lat: 61.5380, lon: 8.2300, elevation: 1860 },
        vertical_gain: 730,
        slope_avg_deg: 23,
        aspect: "NE",
        difficulty: "middels",
        description: "Fin tur fra Leirvassbu med oversiktlig terreng.",
    },
    {
        id: "storebjorn",
        name: "Storebjorn",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.6250, lon: 8.4020, name: "Spiterstulen" },
        summit: { lat: 61.6150, lon: 8.4500, elevation: 2222 },
        vertical_gain: 1100,
        slope_avg_deg: 20,
        aspect: "W",
        difficulty: "middels",
        description: "Lang tur over Galdhopiggens brede flanker. Krever god navigering.",
    },
    {
        id: "besshoe",
        name: "Bessho",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.5250, lon: 8.7860, name: "Bessheim" },
        summit: { lat: 61.5179, lon: 8.6873, elevation: 2258 },
        vertical_gain: 1050,
        slope_avg_deg: 22,
        aspect: "E",
        difficulty: "middels",
        description: "Klassisk topptur fra Bessheim med fantastisk utsikt over Gjende.",
    },
    {
        id: "falketind",
        name: "Falketind",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.2858, lon: 8.2612, name: "Tyinkrysset P" },
        summit: { lat: 61.3836, lon: 8.1001, elevation: 2067 },
        vertical_gain: 1000,
        slope_avg_deg: 27,
        aspect: "NW",
        difficulty: "krevende",
        description: "Krevende tur med bratt terreng. Flott randonee for erfarne.",
    },
    {
        id: "knutsholstind",
        name: "Knutsholstinden",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.5500, lon: 8.2500, name: "Leirvassbu" },
        summit: { lat: 61.5600, lon: 8.2800, elevation: 2091 },
        vertical_gain: 960,
        slope_avg_deg: 25,
        aspect: "SW",
        difficulty: "middels-krevende",
        description: "Populaer topptur med fin nedkjoring paa sorsiden.",
    },
    {
        id: "memuru",
        name: "Memurutinden",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.4913, lon: 8.6310, name: "Memurubu" },
        summit: { lat: 61.5673, lon: 8.4774, elevation: 2366 },
        vertical_gain: 1250,
        slope_avg_deg: 28,
        aspect: "N",
        difficulty: "krevende",
        description: "Jotunheimens mest alpine topptur. Kun for erfarne i stabile forhold.",
    },
    {
        id: "galdhopiggen",
        name: "Galdhopiggen",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.6250, lon: 8.4020, name: "Spiterstulen" },
        summit: { lat: 61.6167, lon: 8.2833, elevation: 2469 },
        vertical_gain: 1350,
        slope_avg_deg: 18,
        aspect: "S",
        difficulty: "middels",
        description: "Norges hoyeste fjell. Lang, men moderat tur fra Spiterstulen. Brepassering.",
    },
    {
        id: "glittertind",
        name: "Glittertind",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.6250, lon: 8.4020, name: "Spiterstulen" },
        summit: { lat: 61.6512, lon: 8.5527, elevation: 2452 },
        vertical_gain: 1330,
        slope_avg_deg: 20,
        aspect: "W",
        difficulty: "middels",
        description: "Norges nest hoyeste. Jevne flanker med god skikjoring paa vaarsno.",
    },
    {
        id: "loftet",
        name: "Loftet",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.5500, lon: 8.2500, name: "Leirvassbu" },
        summit: { lat: 61.5570, lon: 8.2100, elevation: 2170 },
        vertical_gain: 1040,
        slope_avg_deg: 24,
        aspect: "SE",
        difficulty: "middels",
        description: "Oversiktlig tur fra Leirvassbu med brede flanker og fin utsikt mot Kyrkja.",
    },
    {
        id: "surtningssue",
        name: "Surtningssui",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.6250, lon: 8.4020, name: "Spiterstulen" },
        summit: { lat: 61.6400, lon: 8.4400, elevation: 2368 },
        vertical_gain: 1250,
        slope_avg_deg: 22,
        aspect: "NE",
        difficulty: "middels",
        description: "Rolig tur fra Spiterstulen med bra snoforhold utover vaaren.",
    },
    {
        id: "nore_illaabre",
        name: "Nordre Illaabreen",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.6250, lon: 8.4020, name: "Spiterstulen" },
        summit: { lat: 61.6350, lon: 8.4200, elevation: 2320 },
        vertical_gain: 1200,
        slope_avg_deg: 25,
        aspect: "S",
        difficulty: "middels-krevende",
        description: "Bratt bre-renne med paalitelig sno. Kort og intens nedkjoring.",
    },
    {
        id: "uradalsegga",
        name: "Uradalstindene",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.5500, lon: 8.2500, name: "Leirvassbu" },
        summit: { lat: 61.5700, lon: 8.2100, elevation: 2116 },
        vertical_gain: 980,
        slope_avg_deg: 27,
        aspect: "E",
        difficulty: "middels-krevende",
        description: "Alpin karakter med bratte renner paa ostsiden. Fin nedkjoring i pudder.",
    },
    {
        id: "svellnosbrean",
        name: "Svellnosbreen",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.6250, lon: 8.4020, name: "Spiterstulen" },
        summit: { lat: 61.6450, lon: 8.4700, elevation: 2210 },
        vertical_gain: 1090,
        slope_avg_deg: 19,
        aspect: "NW",
        difficulty: "middels",
        description: "Bred bre med jevn stigning. Trygt alternativ i usikre forhold.",
    },
    {
        id: "veotinden",
        name: "Veotinden",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.6250, lon: 8.4020, name: "Spiterstulen" },
        summit: { lat: 61.6100, lon: 8.3800, elevation: 2044 },
        vertical_gain: 920,
        slope_avg_deg: 26,
        aspect: "N",
        difficulty: "middels-krevende",
        description: "Kort, bratt tur rett fra Spiterstulen. Nordvendt renne holder snoen lenge.",
    },

    // ═══════════════════════════════════════
    // HURRUNGANE (Varsom region 3028 Jotunheimen)
    // ═══════════════════════════════════════
    {
        id: "store_skagastolstind",
        name: "Store Skagastolstind",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.4830, lon: 7.8110, name: "Turtagro P" },
        summit: { lat: 61.4568, lon: 7.8695, elevation: 2405 },
        vertical_gain: 1650,
        slope_avg_deg: 35,
        aspect: "SE",
        difficulty: "krevende",
        description: "Norges tredje hoyeste fjell. Svaert krevende splitboard-tur med bratt terreng og brepassering.",
    },
    {
        id: "dyrhaugstindane",
        name: "Dyrhaugstindane",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.4830, lon: 7.8110, name: "Turtagro P" },
        summit: { lat: 61.4650, lon: 7.8350, elevation: 2147 },
        vertical_gain: 1400,
        slope_avg_deg: 33,
        aspect: "NE",
        difficulty: "krevende",
        description: "Klassisk couloir-kjoring i Hurrungane. Bratte renner med alpin karakter.",
    },
    {
        id: "stolsnostind",
        name: "Stolsnostind",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.4830, lon: 7.8110, name: "Turtagro P" },
        summit: { lat: 61.4500, lon: 7.8400, elevation: 2074 },
        vertical_gain: 1300,
        slope_avg_deg: 27,
        aspect: "E",
        difficulty: "middels-krevende",
        description: "Populaer og tilgjengelig topptur i Hurrungane. Flott utsikt over Skagastolstindene.",
    },
    {
        id: "fannaraki",
        name: "Fannaraaki",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.4830, lon: 7.8110, name: "Turtagro P" },
        summit: { lat: 61.5166, lon: 7.9086, elevation: 2068 },
        vertical_gain: 1300,
        slope_avg_deg: 22,
        aspect: "W",
        difficulty: "middels",
        description: "Lang bre-tur fra Turtagro via Fannaraakbreen. Moderat terreng, men lang dag.",
    },
    {
        id: "midtmaradalsegga",
        name: "Midtmaradalsegga",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.4830, lon: 7.8110, name: "Turtagro P" },
        summit: { lat: 61.4600, lon: 7.8200, elevation: 1880 },
        vertical_gain: 1100,
        slope_avg_deg: 30,
        aspect: "N",
        difficulty: "krevende",
        description: "Alpin eggtravers i Hurrungane. Krevende terreng med eksponerte partier.",
    },
    {
        id: "ringsdalstinden",
        name: "Ringsdalstinden",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.4830, lon: 7.8110, name: "Turtagro P" },
        summit: { lat: 61.4520, lon: 7.8550, elevation: 1950 },
        vertical_gain: 1200,
        slope_avg_deg: 32,
        aspect: "NE",
        difficulty: "krevende",
        description: "Bratt NO-side med god snosamling. Klassisk randonee for erfarne i Hurrungane.",
    },
    {
        id: "austanbotntind",
        name: "Austanbotntind",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.4830, lon: 7.8110, name: "Turtagro P" },
        summit: { lat: 61.4620, lon: 7.8700, elevation: 2203 },
        vertical_gain: 1450,
        slope_avg_deg: 30,
        aspect: "SW",
        difficulty: "krevende",
        description: "Bratt nedkjoring mot Bandet. Klassisk Hurrungane-tur for erfarne.",
    },
    {
        id: "sentraltind",
        name: "Sentraltind",
        region: "Jotunheimen",
        varsom_region_id: 3028,
        start: { lat: 61.4830, lon: 7.8110, name: "Turtagro P" },
        summit: { lat: 61.4620, lon: 7.8600, elevation: 2348 },
        vertical_gain: 1600,
        slope_avg_deg: 34,
        aspect: "W",
        difficulty: "krevende",
        description: "Teknisk krevende med bratt topparti. Stor fjellopplevelse i Hurrungane.",
    },

    // ═══════════════════════════════════════
    // SUNNMORSALPANE (Varsom region 3023 Romsdal)
    // ═══════════════════════════════════════
    {
        id: "slogen",
        name: "Slogen",
        region: "Sunnmorsalpane",
        varsom_region_id: 3023,
        start: { lat: 62.1970, lon: 6.6400, name: "Urke P" },
        summit: { lat: 62.2081, lon: 6.6728, elevation: 1564 },
        vertical_gain: 1564,
        slope_avg_deg: 28,
        aspect: "N",
        difficulty: "middels-krevende",
        description: "Ikonisk Sunnmore-topp rett fra fjorden. Spektakulaer nedkjoring til Norangsdalen.",
    },
    {
        id: "kolastinden",
        name: "Kolaastinden",
        region: "Sunnmorsalpane",
        varsom_region_id: 3023,
        start: { lat: 62.2910, lon: 6.8405, name: "Strandafjellet P" },
        summit: { lat: 62.2592, lon: 6.3108, elevation: 1432 },
        vertical_gain: 1100,
        slope_avg_deg: 26,
        aspect: "E",
        difficulty: "middels",
        description: "Populaer tur fra Strandafjellet. Bredt, aapent terreng med god snosikkerhet.",
    },
    {
        id: "saudehornet",
        name: "Saudehornet",
        region: "Sunnmorsalpane",
        varsom_region_id: 3023,
        start: { lat: 62.1950, lon: 6.1900, name: "Saebo P" },
        summit: { lat: 62.1800, lon: 6.2100, elevation: 1303 },
        vertical_gain: 1303,
        slope_avg_deg: 25,
        aspect: "NW",
        difficulty: "middels",
        description: "Klassisk fjord-til-topp med panoramautsikt over Hjorundfjorden.",
    },
    {
        id: "jakta",
        name: "Jakta",
        region: "Sunnmorsalpane",
        varsom_region_id: 3023,
        start: { lat: 62.2910, lon: 6.8405, name: "Strandafjellet P" },
        summit: { lat: 62.2800, lon: 6.8600, elevation: 1590 },
        vertical_gain: 1250,
        slope_avg_deg: 30,
        aspect: "NE",
        difficulty: "middels-krevende",
        description: "Bratt og krevende med fantastiske renner. Sunnmores mest kjente couloir-tur.",
    },
    {
        id: "brekketinden",
        name: "Brekketindane",
        region: "Sunnmorsalpane",
        varsom_region_id: 3023,
        start: { lat: 62.2910, lon: 6.8405, name: "Strandafjellet P" },
        summit: { lat: 62.2700, lon: 6.8100, elevation: 1480 },
        vertical_gain: 1150,
        slope_avg_deg: 28,
        aspect: "N",
        difficulty: "middels-krevende",
        description: "Fin eggtur med flere nedkjoringsalternativer. God snosamling nordvendt.",
    },
    {
        id: "dalegubben",
        name: "Dalegubben",
        region: "Sunnmorsalpane",
        varsom_region_id: 3023,
        start: { lat: 62.2000, lon: 6.1300, name: "Orsta P" },
        summit: { lat: 62.2150, lon: 6.1600, elevation: 1362 },
        vertical_gain: 1100,
        slope_avg_deg: 24,
        aspect: "W",
        difficulty: "middels",
        description: "Tilgjengelig tur med jevn stigning. Bra for dager med moderat vind.",
    },
    {
        id: "roaldshornet",
        name: "Roaldshornet",
        region: "Sunnmorsalpane",
        varsom_region_id: 3023,
        start: { lat: 62.3100, lon: 6.4200, name: "Glomset P" },
        summit: { lat: 62.2900, lon: 6.4500, elevation: 1280 },
        vertical_gain: 1280,
        slope_avg_deg: 26,
        aspect: "SE",
        difficulty: "middels",
        description: "Enkel tilgang og god nedkjoring. Populaert maal for dagstur fra Aalesund.",
    },
    {
        id: "saksa",
        name: "Saksa",
        region: "Sunnmorsalpane",
        varsom_region_id: 3023,
        start: { lat: 62.1970, lon: 6.6400, name: "Urke P" },
        summit: { lat: 62.2050, lon: 6.6100, elevation: 1073 },
        vertical_gain: 1073,
        slope_avg_deg: 30,
        aspect: "S",
        difficulty: "middels-krevende",
        description: "Bratt fjellside med spektakulaer utsikt over Hjorundfjorden. Kort, men intens.",
    },
    {
        id: "smoerstabbtindane",
        name: "Smorstabbtindane",
        region: "Sunnmorsalpane",
        varsom_region_id: 3023,
        start: { lat: 62.2500, lon: 6.9000, name: "Langedalen P" },
        summit: { lat: 62.2650, lon: 6.9200, elevation: 1630 },
        vertical_gain: 1300,
        slope_avg_deg: 27,
        aspect: "NW",
        difficulty: "middels-krevende",
        description: "Alpint terreng med flere toppvalg. Lang dag i storslaatt landskap.",
    },
    {
        id: "kvitegga",
        name: "Kvitegga",
        region: "Sunnmorsalpane",
        varsom_region_id: 3023,
        start: { lat: 62.2300, lon: 6.9500, name: "Hellesylt P" },
        summit: { lat: 62.2200, lon: 6.9800, elevation: 1420 },
        vertical_gain: 1420,
        slope_avg_deg: 22,
        aspect: "SW",
        difficulty: "middels",
        description: "Lang, men moderat tur med fin utsikt over Geirangerfjorden.",
    },
];
