"""
Kjente splitboard-/randonée-turer i Hemsedal, Jotunheimen, Hurrungane og Sunnmørsalpane.
Hver tur har start (parkering), topp, og metadata.
"""

TOURS = [
    # ═══════════════════════════════════════
    # HEMSEDAL (Varsom region 3027 Hallingdal)
    # ═══════════════════════════════════════
    {
        "id": "hemsedal_tinden",
        "name": "Hemsedal Tinden (Storetinden)",
        "region": "Hemsedal",
        "varsom_region_id": 3027,
        "start": {"lat": 60.8600, "lon": 8.3900, "name": "Hemsedal sentrum P"},
        "summit": {"lat": 60.8850, "lon": 8.3400, "elevation": 1487},
        "vertical_gain": 950,
        "slope_avg_deg": 25,
        "aspect": "NE",
        "difficulty": "middels",
        "description": "Klassiker i Hemsedal. Bredt, åpent terreng med flere rennevalg.",
    },
    {
        "id": "rogjin",
        "name": "Røgjin",
        "region": "Hemsedal",
        "varsom_region_id": 3027,
        "start": {"lat": 60.9170, "lon": 8.2690, "name": "Hydnestølen P"},
        "summit": {"lat": 60.9380, "lon": 8.2450, "elevation": 1523},
        "vertical_gain": 850,
        "slope_avg_deg": 22,
        "aspect": "E",
        "difficulty": "lett-middels",
        "description": "Populær tur med jevn stigning. Godt egnet for nybegynnere.",
    },
    {
        "id": "skogshorn",
        "name": "Skogshorn",
        "region": "Hemsedal",
        "varsom_region_id": 3027,
        "start": {"lat": 60.8200, "lon": 8.4500, "name": "Skogshorn P"},
        "summit": {"lat": 60.8350, "lon": 8.4200, "elevation": 1728},
        "vertical_gain": 1100,
        "slope_avg_deg": 28,
        "aspect": "SE",
        "difficulty": "middels-krevende",
        "description": "Ikonisk fjell med bratt topparti. Fantastisk utsikt over Hemsedal.",
    },
    {
        "id": "vesletinden_hemsedal",
        "name": "Vesletinden",
        "region": "Hemsedal",
        "varsom_region_id": 3027,
        "start": {"lat": 60.8750, "lon": 8.4100, "name": "Grøndalen P"},
        "summit": {"lat": 60.8900, "lon": 8.3800, "elevation": 1325},
        "vertical_gain": 650,
        "slope_avg_deg": 20,
        "aspect": "N",
        "difficulty": "lett",
        "description": "Fin nybegynnertur med moderat terreng.",
    },
    {
        "id": "ranastongi",
        "name": "Ranastongi",
        "region": "Hemsedal",
        "varsom_region_id": 3027,
        "start": {"lat": 60.8100, "lon": 8.3200, "name": "Ulsåk P"},
        "summit": {"lat": 60.7950, "lon": 8.2900, "elevation": 1414},
        "vertical_gain": 800,
        "slope_avg_deg": 24,
        "aspect": "NW",
        "difficulty": "middels",
        "description": "Rolig tur med god tilgang til variert terreng.",
    },
    {
        "id": "totteskogen",
        "name": "Totteskogen",
        "region": "Hemsedal",
        "varsom_region_id": 3027,
        "start": {"lat": 60.8750, "lon": 8.4100, "name": "Grøndalen P"},
        "summit": {"lat": 60.8680, "lon": 8.3600, "elevation": 1450},
        "vertical_gain": 780,
        "slope_avg_deg": 22,
        "aspect": "W",
        "difficulty": "lett-middels",
        "description": "Fin tur i skoggrensen med trygge nedkjøringer i Grøndalen.",
    },
    {
        "id": "storehoe",
        "name": "Storehø",
        "region": "Hemsedal",
        "varsom_region_id": 3027,
        "start": {"lat": 60.9300, "lon": 8.3100, "name": "Tuv P"},
        "summit": {"lat": 60.9500, "lon": 8.2800, "elevation": 1546},
        "vertical_gain": 900,
        "slope_avg_deg": 20,
        "aspect": "SE",
        "difficulty": "lett-middels",
        "description": "Oversiktlig terreng med god oversikt. Trygt valg i usikre forhold.",
    },
    {
        "id": "groendalsfjellet",
        "name": "Grøndalsfjellet",
        "region": "Hemsedal",
        "varsom_region_id": 3027,
        "start": {"lat": 60.8750, "lon": 8.4100, "name": "Grøndalen P"},
        "summit": {"lat": 60.8950, "lon": 8.4300, "elevation": 1380},
        "vertical_gain": 700,
        "slope_avg_deg": 18,
        "aspect": "NW",
        "difficulty": "lett",
        "description": "Kort og enkel tur med fine skiforhold. Bra alternativ for familier.",
    },
    {
        "id": "hemsedalsfjellet",
        "name": "Hemsedalsfjellet via Solheisen",
        "region": "Hemsedal",
        "varsom_region_id": 3027,
        "start": {"lat": 60.8850, "lon": 8.3500, "name": "Solheisen P"},
        "summit": {"lat": 60.9050, "lon": 8.3200, "elevation": 1580},
        "vertical_gain": 1000,
        "slope_avg_deg": 26,
        "aspect": "N",
        "difficulty": "middels",
        "description": "Variert tur fra skisenteret med tilgang til bakketerreng og off-piste.",
    },
    {
        "id": "hydnefossen",
        "name": "Hydnefossen-området",
        "region": "Hemsedal",
        "varsom_region_id": 3027,
        "start": {"lat": 60.9170, "lon": 8.2690, "name": "Hydnestølen P"},
        "summit": {"lat": 60.9250, "lon": 8.2300, "elevation": 1610},
        "vertical_gain": 950,
        "slope_avg_deg": 24,
        "aspect": "NE",
        "difficulty": "middels",
        "description": "Spektakulært terreng nær Hydnefossen. Flere rennevalg i bratt fjellside.",
    },

    # ═══════════════════════════════════════
    # JOTUNHEIMEN (Varsom region 3028)
    # ═══════════════════════════════════════
    {
        "id": "leirvassbu_area",
        "name": "Kyrkja fra Leirvassbu",
        "region": "Jotunheimen",
        "varsom_region_id": 3028,
        "start": {"lat": 61.4700, "lon": 8.2200, "name": "Leirvassbu"},
        "summit": {"lat": 61.4950, "lon": 8.1800, "elevation": 2032},
        "vertical_gain": 900,
        "slope_avg_deg": 26,
        "aspect": "S",
        "difficulty": "middels-krevende",
        "description": "Storslått alpint terreng. Kyrkja er en av Jotunheimens flotteste topper.",
    },
    {
        "id": "bukkeholstinden",
        "name": "Bukkeholstinden",
        "region": "Jotunheimen",
        "varsom_region_id": 3028,
        "start": {"lat": 61.4700, "lon": 8.2200, "name": "Leirvassbu"},
        "summit": {"lat": 61.4600, "lon": 8.1900, "elevation": 1860},
        "vertical_gain": 730,
        "slope_avg_deg": 23,
        "aspect": "NE",
        "difficulty": "middels",
        "description": "Fin tur fra Leirvassbu med oversiktlig terreng.",
    },
    {
        "id": "storebjorn",
        "name": "Storebjørn",
        "region": "Jotunheimen",
        "varsom_region_id": 3028,
        "start": {"lat": 61.5600, "lon": 7.9800, "name": "Spiterstulen"},
        "summit": {"lat": 61.5700, "lon": 8.0500, "elevation": 2222},
        "vertical_gain": 1100,
        "slope_avg_deg": 20,
        "aspect": "W",
        "difficulty": "middels",
        "description": "Lang tur over Galdhøpiggens brede flanker. Krever god navigering.",
    },
    {
        "id": "besshoe",
        "name": "Bessho",
        "region": "Jotunheimen",
        "varsom_region_id": 3028,
        "start": {"lat": 61.4890, "lon": 8.9700, "name": "Bessheim"},
        "summit": {"lat": 61.4800, "lon": 8.9200, "elevation": 2258},
        "vertical_gain": 1050,
        "slope_avg_deg": 22,
        "aspect": "E",
        "difficulty": "middels",
        "description": "Klassisk topptur fra Bessheim med fantastisk utsikt over Gjende.",
    },
    {
        "id": "falketind",
        "name": "Falketind",
        "region": "Jotunheimen",
        "varsom_region_id": 3028,
        "start": {"lat": 61.4400, "lon": 7.9200, "name": "Tyinkrysset P"},
        "summit": {"lat": 61.4500, "lon": 7.9600, "elevation": 2067},
        "vertical_gain": 1000,
        "slope_avg_deg": 27,
        "aspect": "NW",
        "difficulty": "krevende",
        "description": "Krevende tur med bratt terreng. Flott randonée for erfarne.",
    },
    {
        "id": "knutsholstind",
        "name": "Knutsholstinden",
        "region": "Jotunheimen",
        "varsom_region_id": 3028,
        "start": {"lat": 61.4700, "lon": 8.2200, "name": "Leirvassbu"},
        "summit": {"lat": 61.4850, "lon": 8.2500, "elevation": 2091},
        "vertical_gain": 960,
        "slope_avg_deg": 25,
        "aspect": "SW",
        "difficulty": "middels-krevende",
        "description": "Populær topptur med fin nedkjøring på sørsiden.",
    },
    {
        "id": "memuru",
        "name": "Memurutinden",
        "region": "Jotunheimen",
        "varsom_region_id": 3028,
        "start": {"lat": 61.5000, "lon": 8.5100, "name": "Memurubu"},
        "summit": {"lat": 61.4850, "lon": 8.5400, "elevation": 2366},
        "vertical_gain": 1250,
        "slope_avg_deg": 28,
        "aspect": "N",
        "difficulty": "krevende",
        "description": "Jotunheimens mest alpine topptur. Kun for erfarne i stabile forhold.",
    },
    {
        "id": "galdhopiggen",
        "name": "Galdhøpiggen",
        "region": "Jotunheimen",
        "varsom_region_id": 3028,
        "start": {"lat": 61.5600, "lon": 7.9800, "name": "Spiterstulen"},
        "summit": {"lat": 61.6367, "lon": 8.3125, "elevation": 2469},
        "vertical_gain": 1350,
        "slope_avg_deg": 18,
        "aspect": "S",
        "difficulty": "middels",
        "description": "Norges høyeste fjell. Lang, men moderat tur fra Spiterstulen. Brepassering.",
    },
    {
        "id": "glittertind",
        "name": "Glittertind",
        "region": "Jotunheimen",
        "varsom_region_id": 3028,
        "start": {"lat": 61.5600, "lon": 7.9800, "name": "Spiterstulen"},
        "summit": {"lat": 61.6533, "lon": 8.5058, "elevation": 2452},
        "vertical_gain": 1330,
        "slope_avg_deg": 20,
        "aspect": "W",
        "difficulty": "middels",
        "description": "Norges nest høyeste. Jevne flanker med god skikjøring på vårsnø.",
    },
    {
        "id": "loftet",
        "name": "Loftet",
        "region": "Jotunheimen",
        "varsom_region_id": 3028,
        "start": {"lat": 61.4700, "lon": 8.2200, "name": "Leirvassbu"},
        "summit": {"lat": 61.4820, "lon": 8.1600, "elevation": 2170},
        "vertical_gain": 1040,
        "slope_avg_deg": 24,
        "aspect": "SE",
        "difficulty": "middels",
        "description": "Oversiktlig tur fra Leirvassbu med brede flanker og fin utsikt mot Kyrkja.",
    },
    {
        "id": "surtningssue",
        "name": "Surtningssui",
        "region": "Jotunheimen",
        "varsom_region_id": 3028,
        "start": {"lat": 61.5600, "lon": 7.9800, "name": "Spiterstulen"},
        "summit": {"lat": 61.5850, "lon": 8.0200, "elevation": 2368},
        "vertical_gain": 1250,
        "slope_avg_deg": 22,
        "aspect": "NE",
        "difficulty": "middels",
        "description": "Rolig tur fra Spiterstulen med bra snøforhold utover våren.",
    },
    {
        "id": "nore_illaabre",
        "name": "Nordre Illåbreen",
        "region": "Jotunheimen",
        "varsom_region_id": 3028,
        "start": {"lat": 61.5600, "lon": 7.9800, "name": "Spiterstulen"},
        "summit": {"lat": 61.5750, "lon": 8.0000, "elevation": 2320},
        "vertical_gain": 1200,
        "slope_avg_deg": 25,
        "aspect": "S",
        "difficulty": "middels-krevende",
        "description": "Bratt bre-renne med pålitelig snø. Kort og intens nedkjøring.",
    },
    {
        "id": "uradalsegga",
        "name": "Uradalstindene",
        "region": "Jotunheimen",
        "varsom_region_id": 3028,
        "start": {"lat": 61.4700, "lon": 8.2200, "name": "Leirvassbu"},
        "summit": {"lat": 61.5050, "lon": 8.1500, "elevation": 2116},
        "vertical_gain": 980,
        "slope_avg_deg": 27,
        "aspect": "E",
        "difficulty": "middels-krevende",
        "description": "Alpin karakter med bratte renner på østsiden. Fin nedkjøring i pudder.",
    },
    {
        "id": "svellnosbrean",
        "name": "Svellnosbreen",
        "region": "Jotunheimen",
        "varsom_region_id": 3028,
        "start": {"lat": 61.5600, "lon": 7.9800, "name": "Spiterstulen"},
        "summit": {"lat": 61.5950, "lon": 8.0700, "elevation": 2210},
        "vertical_gain": 1090,
        "slope_avg_deg": 19,
        "aspect": "NW",
        "difficulty": "middels",
        "description": "Bred bre med jevn stigning. Trygt alternativ i usikre forhold.",
    },
    {
        "id": "veotinden",
        "name": "Veotinden",
        "region": "Jotunheimen",
        "varsom_region_id": 3028,
        "start": {"lat": 61.5600, "lon": 7.9800, "name": "Spiterstulen"},
        "summit": {"lat": 61.5500, "lon": 8.0100, "elevation": 2044},
        "vertical_gain": 920,
        "slope_avg_deg": 26,
        "aspect": "N",
        "difficulty": "middels-krevende",
        "description": "Kort, bratt tur rett fra Spiterstulen. Nordvendt renne holder snøen lenge.",
    },

    # ═══════════════════════════════════════
    # HURRUNGANE (Varsom region 3028 Jotunheimen)
    # ═══════════════════════════════════════
    {
        "id": "store_skagastolstind",
        "name": "Store Skagastølstind",
        "region": "Jotunheimen",
        "varsom_region_id": 3028,
        "start": {"lat": 61.4850, "lon": 7.8100, "name": "Turtagrø P"},
        "summit": {"lat": 61.4950, "lon": 7.8250, "elevation": 2405},
        "vertical_gain": 1650,
        "slope_avg_deg": 35,
        "aspect": "SE",
        "difficulty": "krevende",
        "description": "Norges tredje høyeste fjell. Svært krevende splitboard-tur med bratt terreng og brepassering.",
    },
    {
        "id": "dyrhaugstindane",
        "name": "Dyrhaugstindane",
        "region": "Jotunheimen",
        "varsom_region_id": 3028,
        "start": {"lat": 61.4850, "lon": 7.8100, "name": "Turtagrø P"},
        "summit": {"lat": 61.4920, "lon": 7.7950, "elevation": 2147},
        "vertical_gain": 1400,
        "slope_avg_deg": 33,
        "aspect": "NE",
        "difficulty": "krevende",
        "description": "Klassisk couloir-kjøring i Hurrungane. Bratte renner med alpin karakter.",
    },
    {
        "id": "stolsnostind",
        "name": "Stølsnostind",
        "region": "Jotunheimen",
        "varsom_region_id": 3028,
        "start": {"lat": 61.4850, "lon": 7.8100, "name": "Turtagrø P"},
        "summit": {"lat": 61.4780, "lon": 7.7900, "elevation": 2074},
        "vertical_gain": 1300,
        "slope_avg_deg": 27,
        "aspect": "E",
        "difficulty": "middels-krevende",
        "description": "Populær og tilgjengelig topptur i Hurrungane. Flott utsikt over Skagastølstindene.",
    },
    {
        "id": "fannaraki",
        "name": "Fannaråki",
        "region": "Jotunheimen",
        "varsom_region_id": 3028,
        "start": {"lat": 61.4850, "lon": 7.8100, "name": "Turtagrø P"},
        "summit": {"lat": 61.5150, "lon": 7.9050, "elevation": 2068},
        "vertical_gain": 1300,
        "slope_avg_deg": 22,
        "aspect": "W",
        "difficulty": "middels",
        "description": "Lang bre-tur fra Turtagrø via Fannaråkbreen. Moderat terreng, men lang dag.",
    },
    {
        "id": "midtmaradalsegga",
        "name": "Midtmaradalsegga",
        "region": "Jotunheimen",
        "varsom_region_id": 3028,
        "start": {"lat": 61.4850, "lon": 7.8100, "name": "Turtagrø P"},
        "summit": {"lat": 61.4880, "lon": 7.7800, "elevation": 1880},
        "vertical_gain": 1100,
        "slope_avg_deg": 30,
        "aspect": "N",
        "difficulty": "krevende",
        "description": "Alpin eggtravers i Hurrungane. Krevende terreng med eksponerte partier.",
    },
    {
        "id": "ringsdalstinden",
        "name": "Ringsdalstinden",
        "region": "Jotunheimen",
        "varsom_region_id": 3028,
        "start": {"lat": 61.4850, "lon": 7.8100, "name": "Turtagrø P"},
        "summit": {"lat": 61.4750, "lon": 7.8300, "elevation": 1950},
        "vertical_gain": 1200,
        "slope_avg_deg": 32,
        "aspect": "NE",
        "difficulty": "krevende",
        "description": "Bratt NØ-side med god snøsamling. Klassisk randonée for erfarne i Hurrungane.",
    },
    {
        "id": "austanbotntind",
        "name": "Austanbotntind",
        "region": "Jotunheimen",
        "varsom_region_id": 3028,
        "start": {"lat": 61.4850, "lon": 7.8100, "name": "Turtagrø P"},
        "summit": {"lat": 61.4900, "lon": 7.8400, "elevation": 2203},
        "vertical_gain": 1450,
        "slope_avg_deg": 30,
        "aspect": "SW",
        "difficulty": "krevende",
        "description": "Bratt nedkjøring mot Bandet. Klassisk Hurrungane-tur for erfarne.",
    },
    {
        "id": "sentraltind",
        "name": "Sentraltind",
        "region": "Jotunheimen",
        "varsom_region_id": 3028,
        "start": {"lat": 61.4850, "lon": 7.8100, "name": "Turtagrø P"},
        "summit": {"lat": 61.4980, "lon": 7.8150, "elevation": 2348},
        "vertical_gain": 1600,
        "slope_avg_deg": 34,
        "aspect": "W",
        "difficulty": "krevende",
        "description": "Teknisk krevende med bratt topparti. Stor fjellopplevelse i Hurrungane.",
    },

    # ═══════════════════════════════════════
    # SUNNMØRSALPANE (Varsom region 3023 Romsdal)
    # ═══════════════════════════════════════
    {
        "id": "slogen",
        "name": "Slogen",
        "region": "Sunnmørsalpane",
        "varsom_region_id": 3023,
        "start": {"lat": 62.1700, "lon": 6.2600, "name": "Urke P"},
        "summit": {"lat": 62.1580, "lon": 6.2900, "elevation": 1564},
        "vertical_gain": 1564,
        "slope_avg_deg": 28,
        "aspect": "N",
        "difficulty": "middels-krevende",
        "description": "Ikonisk Sunnmøre-topp rett fra fjorden. Spektakulær nedkjøring til Norangsdalen.",
    },
    {
        "id": "kolastinden",
        "name": "Kolåstinden",
        "region": "Sunnmørsalpane",
        "varsom_region_id": 3023,
        "start": {"lat": 62.1250, "lon": 6.8300, "name": "Strandafjellet P"},
        "summit": {"lat": 62.1350, "lon": 6.8000, "elevation": 1432},
        "vertical_gain": 1100,
        "slope_avg_deg": 26,
        "aspect": "E",
        "difficulty": "middels",
        "description": "Populær tur fra Strandafjellet. Bredt, åpent terreng med god snøsikkerhet.",
    },
    {
        "id": "saudehornet",
        "name": "Saudehornet",
        "region": "Sunnmørsalpane",
        "varsom_region_id": 3023,
        "start": {"lat": 62.1400, "lon": 6.1200, "name": "Sæbø P"},
        "summit": {"lat": 62.1250, "lon": 6.1500, "elevation": 1303},
        "vertical_gain": 1303,
        "slope_avg_deg": 25,
        "aspect": "NW",
        "difficulty": "middels",
        "description": "Klassisk fjord-til-topp med panoramautsikt over Hjørundfjorden.",
    },
    {
        "id": "jakta",
        "name": "Jakta",
        "region": "Sunnmørsalpane",
        "varsom_region_id": 3023,
        "start": {"lat": 62.1250, "lon": 6.8300, "name": "Strandafjellet P"},
        "summit": {"lat": 62.1180, "lon": 6.8500, "elevation": 1590},
        "vertical_gain": 1250,
        "slope_avg_deg": 30,
        "aspect": "NE",
        "difficulty": "middels-krevende",
        "description": "Bratt og krevende med fantastiske renner. Sunnmøres mest kjente couloir-tur.",
    },
    {
        "id": "brekketinden",
        "name": "Brekketindane",
        "region": "Sunnmørsalpane",
        "varsom_region_id": 3023,
        "start": {"lat": 62.1250, "lon": 6.8300, "name": "Strandafjellet P"},
        "summit": {"lat": 62.1100, "lon": 6.7800, "elevation": 1480},
        "vertical_gain": 1150,
        "slope_avg_deg": 28,
        "aspect": "N",
        "difficulty": "middels-krevende",
        "description": "Fin eggtur med flere nedkjøringsalternativer. God snøsamling nordvendt.",
    },
    {
        "id": "dalegubben",
        "name": "Dalegubben",
        "region": "Sunnmørsalpane",
        "varsom_region_id": 3023,
        "start": {"lat": 62.1050, "lon": 6.6800, "name": "Ørsta P"},
        "summit": {"lat": 62.1150, "lon": 6.7100, "elevation": 1362},
        "vertical_gain": 1100,
        "slope_avg_deg": 24,
        "aspect": "W",
        "difficulty": "middels",
        "description": "Tilgjengelig tur med jevn stigning. Bra for dager med moderat vind.",
    },
    {
        "id": "roaldshornet",
        "name": "Roaldshornet",
        "region": "Sunnmørsalpane",
        "varsom_region_id": 3023,
        "start": {"lat": 62.2200, "lon": 6.3500, "name": "Glomset P"},
        "summit": {"lat": 62.2100, "lon": 6.3800, "elevation": 1280},
        "vertical_gain": 1280,
        "slope_avg_deg": 26,
        "aspect": "SE",
        "difficulty": "middels",
        "description": "Enkel tilgang og god nedkjøring. Populært mål for dagstur fra Ålesund.",
    },
    {
        "id": "saksa",
        "name": "Saksa",
        "region": "Sunnmørsalpane",
        "varsom_region_id": 3023,
        "start": {"lat": 62.1900, "lon": 6.1000, "name": "Bondalen P"},
        "summit": {"lat": 62.1750, "lon": 6.1300, "elevation": 1073},
        "vertical_gain": 1073,
        "slope_avg_deg": 30,
        "aspect": "S",
        "difficulty": "middels-krevende",
        "description": "Bratt fjellside med spektakulær utsikt over Hjørundfjorden. Kort, men intens.",
    },
    {
        "id": "smoerstabbtindane",
        "name": "Smørstabbtindane",
        "region": "Sunnmørsalpane",
        "varsom_region_id": 3023,
        "start": {"lat": 62.0800, "lon": 6.9000, "name": "Langedalen P"},
        "summit": {"lat": 62.0950, "lon": 6.9200, "elevation": 1630},
        "vertical_gain": 1300,
        "slope_avg_deg": 27,
        "aspect": "NW",
        "difficulty": "middels-krevende",
        "description": "Alpint terreng med flere toppvalg. Lang dag i storslått landskap.",
    },
    {
        "id": "kvitegga",
        "name": "Kvitegga",
        "region": "Sunnmørsalpane",
        "varsom_region_id": 3023,
        "start": {"lat": 62.1500, "lon": 6.9500, "name": "Hellesylt P"},
        "summit": {"lat": 62.1350, "lon": 6.9800, "elevation": 1420},
        "vertical_gain": 1420,
        "slope_avg_deg": 22,
        "aspect": "SW",
        "difficulty": "middels",
        "description": "Lang, men moderat tur med fin utsikt over Geirangerfjorden.",
    },
]


def get_tours_by_region(region: str = None) -> list:
    if region:
        return [t for t in TOURS if t["region"].lower() == region.lower()]
    return TOURS


def get_tour_by_id(tour_id: str) -> dict | None:
    for t in TOURS:
        if t["id"] == tour_id:
            return t
    return None
